Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -94,13 +94,14 @@ jobs:
 
       - name: Prepare and Build Kernel Module
         run: |
-          cd ./builds/${ROOT_DIR}/oneplus12_v
-          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- modules_prepare
-          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- M=arch/arm64/geniezone modules
-          if [ ! -f "arch/arm64/geniezone/gzvm.ko" ]; then
-            echo "Error: Module gzvm.ko not built!"
-            exit 1
-          fi
+           cd ./builds/${ROOT_DIR}/oneplus12_v
+           make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- gki_defconfig
+           make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- modules_prepare
+           make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- M=arch/arm64/geniezone modules
+           if [ ! -f "arch/arm64/geniezone/gzvm.ko" ]; then
+             echo "Error: Module gzvm.ko not built!"
+             exit 1
+           fi
 
       - name: Add SUSFS
         run: |
